server:
  port: 6201

spring:
  application:
    name: microservice-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:7201/eureka/,http://eureka02:7202/eureka/
    healthcheck:
      enabled: true
  instance:
    instance-id: zuul网关服务-6201
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5

zuul:
  ignored-services: microservice-plate
  routes:
    prefix: /zuul
    order:
      serviceId: microservice-plate
      path: /plate/**
