server:
  port: 8201

spring:
  application:
    name: microservice-plate
  datasource: # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000

# 客户端注册到eureka服务列表
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:7201/eureka/,http://eureka02:7202/eureka/
    healthcheck:
      enabled: true
  instance:
    instance-id: 车牌识别服务-8201
    prefer-ip-address: true # 访问路径可显示IP地址
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5

# 整合mybatis
mybatis-plus:
  # 搜索指定包别名
  type-aliases-package: com.fly.springcloud
  # 该配置请和 type-aliases-package 一起使用，如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象 。
  type-aliases-super-type: java.lang.Object
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 配置的缓存的全局开关
    cache-enabled: true
    # 延时加载的开关
    lazy-loading-enabled: true
    # 开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    multiple-result-sets-enabled: true
    use-generated-keys: true
    default-statement-timeout: 60
    default-fetch-size: 100

# 配置hystrix dashboard的url访问
# 开启指标流端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
