server:
  port: 9201

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka01:7201/eureka/,http://eureka02:7202/eureka/
  instance:
    instance-id: 消费方服务-9201
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
  application:
    name: ribbon-client

# feign和ribbon结合，指定策略。feign默认的是轮询的策略，这里的配置可以自定义
MICROSERVICE-PLATE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  hystrix:
    enabled: true
